apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZ29vZHZpZGVvLXVwbG9hZC1yZHMuY3puOThub3p2emEzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3VwbG9hZA==
  ACCESS_KEY: QUtJQTU3WllHV09UUkJGNkdERFo=
  SECRET_ACCESS_KEY: V3lzSVJXZUJsM3dPcFl0WEs3V2RBaEZHUmhLUTJHTVpHd2pPQ01tSw==
  BUCKET_NAME: Z29vZHZpZGVvLXZpZGVvcy11cGxvYWQ=